import React from 'react'

import { storiesOf } from '@storybook/react'

import Heading from '../Heading'

storiesOf('Heading', module)
  .add('default', () => (
    <Heading>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam delectus unde porro doloribus, accusantium quasi illum aperiam architecto adipisci voluptatibus illo velit modi expedita ipsa perspiciatis sed iste sit repellat, alias. Soluta sed, cumque, fugit est odit ipsam inventore porro officia repellendus voluptatem neque error. Mollitia quam cupiditate doloribus aliquid. Dolore praesentium, rerum, consequatur tenetur sapiente aliquid distinctio expedita repudiandae dolor quas maxime. Molestiae aspernatur ea beatae velit ratione neque, commodi blanditiis voluptate corporis ex cum dolores eaque animi eveniet odit assumenda deleniti unde corrupti facere veniam quibusdam. Ex at repudiandae iure quae, natus illum eveniet eaque, autem rem dicta, aliquid! Nobis voluptates, ut quae soluta laborum eius cumque minima perferendis ab suscipit. Accusamus atque optio amet esse assumenda, illum temporibus sit veniam minima qui est explicabo error placeat consectetur, ea corporis dignissimos aliquam tempore nobis nemo impedit illo recusandae sint. Eligendi laboriosam, neque fuga, debitis, quasi et corporis ipsam nihil tempora perspiciatis, impedit at! Quam atque nemo maiores rem repellat quae, aliquid, tempora sed ipsam adipisci tenetur explicabo, deleniti debitis. Iure sequi, illo, cum sit obcaecati nostrum molestias aspernatur odio aliquam adipisci esse cupiditate quis nulla nobis impedit qui ab magni natus voluptas saepe et! Ipsum praesentium in tempora.
    </Heading>
  )).add('with h1', () => (
    <Heading.h1>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam delectus unde porro doloribus, accusantium quasi illum aperiam architecto adipisci voluptatibus illo velit modi expedita ipsa perspiciatis sed iste sit repellat, alias. Soluta sed, cumque, fugit est odit ipsam inventore porro officia repellendus voluptatem neque error. Mollitia quam cupiditate doloribus aliquid. Dolore praesentium, rerum, consequatur tenetur sapiente aliquid distinctio expedita repudiandae dolor quas maxime. Molestiae aspernatur ea beatae velit ratione neque, commodi blanditiis voluptate corporis ex cum dolores eaque animi eveniet odit assumenda deleniti unde corrupti facere veniam quibusdam. Ex at repudiandae iure quae, natus illum eveniet eaque, autem rem dicta, aliquid! Nobis voluptates, ut quae soluta laborum eius cumque minima perferendis ab suscipit. Accusamus atque optio amet esse assumenda, illum temporibus sit veniam minima qui est explicabo error placeat consectetur, ea corporis dignissimos aliquam tempore nobis nemo impedit illo recusandae sint. Eligendi laboriosam, neque fuga, debitis, quasi et corporis ipsam nihil tempora perspiciatis, impedit at! Quam atque nemo maiores rem repellat quae, aliquid, tempora sed ipsam adipisci tenetur explicabo, deleniti debitis. Iure sequi, illo, cum sit obcaecati nostrum molestias aspernatur odio aliquam adipisci esse cupiditate quis nulla nobis impedit qui ab magni natus voluptas saepe et! Ipsum praesentium in tempora.
    </Heading.h1>
  )).add('with h2', () => (
    <Heading.h2>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam delectus unde porro doloribus, accusantium quasi illum aperiam architecto adipisci voluptatibus illo velit modi expedita ipsa perspiciatis sed iste sit repellat, alias. Soluta sed, cumque, fugit est odit ipsam inventore porro officia repellendus voluptatem neque error. Mollitia quam cupiditate doloribus aliquid. Dolore praesentium, rerum, consequatur tenetur sapiente aliquid distinctio expedita repudiandae dolor quas maxime. Molestiae aspernatur ea beatae velit ratione neque, commodi blanditiis voluptate corporis ex cum dolores eaque animi eveniet odit assumenda deleniti unde corrupti facere veniam quibusdam. Ex at repudiandae iure quae, natus illum eveniet eaque, autem rem dicta, aliquid! Nobis voluptates, ut quae soluta laborum eius cumque minima perferendis ab suscipit. Accusamus atque optio amet esse assumenda, illum temporibus sit veniam minima qui est explicabo error placeat consectetur, ea corporis dignissimos aliquam tempore nobis nemo impedit illo recusandae sint. Eligendi laboriosam, neque fuga, debitis, quasi et corporis ipsam nihil tempora perspiciatis, impedit at! Quam atque nemo maiores rem repellat quae, aliquid, tempora sed ipsam adipisci tenetur explicabo, deleniti debitis. Iure sequi, illo, cum sit obcaecati nostrum molestias aspernatur odio aliquam adipisci esse cupiditate quis nulla nobis impedit qui ab magni natus voluptas saepe et! Ipsum praesentium in tempora.
    </Heading.h2>
  )).add('with h3', () => (
    <Heading.h3>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam delectus unde porro doloribus, accusantium quasi illum aperiam architecto adipisci voluptatibus illo velit modi expedita ipsa perspiciatis sed iste sit repellat, alias. Soluta sed, cumque, fugit est odit ipsam inventore porro officia repellendus voluptatem neque error. Mollitia quam cupiditate doloribus aliquid. Dolore praesentium, rerum, consequatur tenetur sapiente aliquid distinctio expedita repudiandae dolor quas maxime. Molestiae aspernatur ea beatae velit ratione neque, commodi blanditiis voluptate corporis ex cum dolores eaque animi eveniet odit assumenda deleniti unde corrupti facere veniam quibusdam. Ex at repudiandae iure quae, natus illum eveniet eaque, autem rem dicta, aliquid! Nobis voluptates, ut quae soluta laborum eius cumque minima perferendis ab suscipit. Accusamus atque optio amet esse assumenda, illum temporibus sit veniam minima qui est explicabo error placeat consectetur, ea corporis dignissimos aliquam tempore nobis nemo impedit illo recusandae sint. Eligendi laboriosam, neque fuga, debitis, quasi et corporis ipsam nihil tempora perspiciatis, impedit at! Quam atque nemo maiores rem repellat quae, aliquid, tempora sed ipsam adipisci tenetur explicabo, deleniti debitis. Iure sequi, illo, cum sit obcaecati nostrum molestias aspernatur odio aliquam adipisci esse cupiditate quis nulla nobis impedit qui ab magni natus voluptas saepe et! Ipsum praesentium in tempora.
    </Heading.h3>
  ))
  .add('with h4', () => (
    <Heading.h4>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam delectus unde porro doloribus, accusantium quasi illum aperiam architecto adipisci voluptatibus illo velit modi expedita ipsa perspiciatis sed iste sit repellat, alias. Soluta sed, cumque, fugit est odit ipsam inventore porro officia repellendus voluptatem neque error. Mollitia quam cupiditate doloribus aliquid. Dolore praesentium, rerum, consequatur tenetur sapiente aliquid distinctio expedita repudiandae dolor quas maxime. Molestiae aspernatur ea beatae velit ratione neque, commodi blanditiis voluptate corporis ex cum dolores eaque animi eveniet odit assumenda deleniti unde corrupti facere veniam quibusdam. Ex at repudiandae iure quae, natus illum eveniet eaque, autem rem dicta, aliquid! Nobis voluptates, ut quae soluta laborum eius cumque minima perferendis ab suscipit. Accusamus atque optio amet esse assumenda, illum temporibus sit veniam minima qui est explicabo error placeat consectetur, ea corporis dignissimos aliquam tempore nobis nemo impedit illo recusandae sint. Eligendi laboriosam, neque fuga, debitis, quasi et corporis ipsam nihil tempora perspiciatis, impedit at! Quam atque nemo maiores rem repellat quae, aliquid, tempora sed ipsam adipisci tenetur explicabo, deleniti debitis. Iure sequi, illo, cum sit obcaecati nostrum molestias aspernatur odio aliquam adipisci esse cupiditate quis nulla nobis impedit qui ab magni natus voluptas saepe et! Ipsum praesentium in tempora.
    </Heading.h4>
  ))
  .add('with h5', () => (
    <Heading.h5>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam delectus unde porro doloribus, accusantium quasi illum aperiam architecto adipisci voluptatibus illo velit modi expedita ipsa perspiciatis sed iste sit repellat, alias. Soluta sed, cumque, fugit est odit ipsam inventore porro officia repellendus voluptatem neque error. Mollitia quam cupiditate doloribus aliquid. Dolore praesentium, rerum, consequatur tenetur sapiente aliquid distinctio expedita repudiandae dolor quas maxime. Molestiae aspernatur ea beatae velit ratione neque, commodi blanditiis voluptate corporis ex cum dolores eaque animi eveniet odit assumenda deleniti unde corrupti facere veniam quibusdam. Ex at repudiandae iure quae, natus illum eveniet eaque, autem rem dicta, aliquid! Nobis voluptates, ut quae soluta laborum eius cumque minima perferendis ab suscipit. Accusamus atque optio amet esse assumenda, illum temporibus sit veniam minima qui est explicabo error placeat consectetur, ea corporis dignissimos aliquam tempore nobis nemo impedit illo recusandae sint. Eligendi laboriosam, neque fuga, debitis, quasi et corporis ipsam nihil tempora perspiciatis, impedit at! Quam atque nemo maiores rem repellat quae, aliquid, tempora sed ipsam adipisci tenetur explicabo, deleniti debitis. Iure sequi, illo, cum sit obcaecati nostrum molestias aspernatur odio aliquam adipisci esse cupiditate quis nulla nobis impedit qui ab magni natus voluptas saepe et! Ipsum praesentium in tempora.
    </Heading.h5>
  ))
  .add('with h6', () => (
    <Heading.h6>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam delectus unde porro doloribus, accusantium quasi illum aperiam architecto adipisci voluptatibus illo velit modi expedita ipsa perspiciatis sed iste sit repellat, alias. Soluta sed, cumque, fugit est odit ipsam inventore porro officia repellendus voluptatem neque error. Mollitia quam cupiditate doloribus aliquid. Dolore praesentium, rerum, consequatur tenetur sapiente aliquid distinctio expedita repudiandae dolor quas maxime. Molestiae aspernatur ea beatae velit ratione neque, commodi blanditiis voluptate corporis ex cum dolores eaque animi eveniet odit assumenda deleniti unde corrupti facere veniam quibusdam. Ex at repudiandae iure quae, natus illum eveniet eaque, autem rem dicta, aliquid! Nobis voluptates, ut quae soluta laborum eius cumque minima perferendis ab suscipit. Accusamus atque optio amet esse assumenda, illum temporibus sit veniam minima qui est explicabo error placeat consectetur, ea corporis dignissimos aliquam tempore nobis nemo impedit illo recusandae sint. Eligendi laboriosam, neque fuga, debitis, quasi et corporis ipsam nihil tempora perspiciatis, impedit at! Quam atque nemo maiores rem repellat quae, aliquid, tempora sed ipsam adipisci tenetur explicabo, deleniti debitis. Iure sequi, illo, cum sit obcaecati nostrum molestias aspernatur odio aliquam adipisci esse cupiditate quis nulla nobis impedit qui ab magni natus voluptas saepe et! Ipsum praesentium in tempora.
    </Heading.h6>
  ))
